apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - daemonset.yaml
  - service.yaml
  - serviceaccount.yaml
  - sres-secret-sealed.yaml
  - test-connection.yaml
  - harbor-secret-sealed.yaml
  - psp.yaml
