---
# Source: fluent-bit/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "release-name-fluent-bit-test-connection"
  labels:
    helm.sh/chart: fluent-bit-0.24.0
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.0.9"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: "sres.web.boeing.com:5000/busybox:latest"
      imagePullPolicy: Always
      command: ['wget']
      args: ['release-name-fluent-bit:2020']
  imagePullSecrets:
    - name: sres-registry
  restartPolicy: Never
